//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Name="wsScrc.XMLPortType", Namespace="urn:wsScrc.XML", ConfigurationName="wsScrcXMLPortType")]
public interface wsScrcXMLPortType
{
    
    // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
    [System.ServiceModel.OperationContractAttribute(Action="urn:wsScrc.XML#XML")]
    //[System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    XMLResponse XML(XMLRequest request);
    
    // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
    [System.ServiceModel.OperationContractAttribute(Action="urn:wsScrc.XMLAreaLivre#XMLAreaLivre")]
    //[System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    XMLAreaLivreResponse XMLAreaLivre(XMLAreaLivreRequest request);
    
    // CODEGEN: Gerando contrato de mensagem porque o namespace do conteúdo (urn:wsScrc.monitor) da mensagem monitorRequest não corresponde ao valor padrão (urn:wsScrc.XML)
    [System.ServiceModel.OperationContractAttribute(Action="urn:wsScrc.monitor#monitor")]
    //[System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    monitorResponse monitor(monitorRequest request);
}

//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="XML", WrapperNamespace="urn:wsScrc.XML", IsWrapped=true)]
public partial class XMLRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string ip;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string sistemaOrigem;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string transacao;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string agencia;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string matricula;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string cpfCnpj;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string tipoPessoa;
    
    public XMLRequest()
    {
    }
    
    public XMLRequest(string ip, string sistemaOrigem, string transacao, string agencia, string matricula, string cpfCnpj, string tipoPessoa)
    {
        this.ip = ip;
        this.sistemaOrigem = sistemaOrigem;
        this.transacao = transacao;
        this.agencia = agencia;
        this.matricula = matricula;
        this.cpfCnpj = cpfCnpj;
        this.tipoPessoa = tipoPessoa;
    }
}

//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="XMLResponse", WrapperNamespace="urn:wsScrc.XML", IsWrapped=true)]
public partial class XMLResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string erro;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string descErro;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string conSerasa;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string xmlResultSerasa;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string xmlResultSistInt;
    
    public XMLResponse()
    {
    }
    
    public XMLResponse(string erro, string descErro, string conSerasa, string xmlResultSerasa, string xmlResultSistInt)
    {
        this.erro = erro;
        this.descErro = descErro;
        this.conSerasa = conSerasa;
        this.xmlResultSerasa = xmlResultSerasa;
        this.xmlResultSistInt = xmlResultSistInt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="XMLAreaLivre", WrapperNamespace="urn:wsScrc.XMLAreaLivre", IsWrapped=true)]
public partial class XMLAreaLivreRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string ip;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string sistemaOrigem;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string transacao;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string agencia;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string matricula;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string cpfCnpj;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public string tipoPessoa;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public string areaLivre;
    
    public XMLAreaLivreRequest()
    {
    }
    
    public XMLAreaLivreRequest(string ip, string sistemaOrigem, string transacao, string agencia, string matricula, string cpfCnpj, string tipoPessoa, string areaLivre)
    {
        this.ip = ip;
        this.sistemaOrigem = sistemaOrigem;
        this.transacao = transacao;
        this.agencia = agencia;
        this.matricula = matricula;
        this.cpfCnpj = cpfCnpj;
        this.tipoPessoa = tipoPessoa;
        this.areaLivre = areaLivre;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="XMLAreaLivreResponse", WrapperNamespace="urn:wsScrc.XMLAreaLivre", IsWrapped=true)]
public partial class XMLAreaLivreResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string erro;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string descErro;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string conSerasa;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string xmlResultSerasa;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string xmlResultSistInt;
    
    public XMLAreaLivreResponse()
    {
    }
    
    public XMLAreaLivreResponse(string erro, string descErro, string conSerasa, string xmlResultSerasa, string xmlResultSistInt)
    {
        this.erro = erro;
        this.descErro = descErro;
        this.conSerasa = conSerasa;
        this.xmlResultSerasa = xmlResultSerasa;
        this.xmlResultSistInt = xmlResultSistInt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="monitor", WrapperNamespace="urn:wsScrc.monitor", IsWrapped=true)]
public partial class monitorRequest
{
    
    public monitorRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="monitorResponse", WrapperNamespace="urn:wsScrc.monitor", IsWrapped=true)]
public partial class monitorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string ipServidor;
    
    public monitorResponse()
    {
    }
    
    public monitorResponse(string ipServidor)
    {
        this.ipServidor = ipServidor;
    }
}
